### ISSUE TITLE
Проблеми редагування

### ISSUE THREAD

**Issue by Katrinkleina** [Katrinkleina/-_21#1]
В кого є які запитання з приводу вимог до оформлення?

**Comment by Darochka** [comment]
В мене є запитання щодо правильності використання тире і дефісу у бібліографічному описі?

**Comment by IrynaPanashiy** [comment]
Я знаю,як це правильно зробити.

**Comment by Katrinkleina** [comment]
Добре, тоді #IrynaPanashiy буде відповідальна за це

**Comment by Katrinkleina** [comment]
Добре, тоді @IrynaPanashiy  буде відповідати за це

**Comment by Darochka** [comment]
А хтось знає як правильно подавати список літератури іноземною мовою, чи є там винятки?

**Comment by OsakaBlue** [comment]
Як зробити той символ, який не дозволяє розривати слова?

**Comment by nataliakendzerska** [comment]
У списку джерел спочатку подають літературу за українським алфавітом, а потім література іноземною мовою в порядку латинського алфавіту.

**Comment by Darochka** [comment]
Потрібно набрати комбінацію Cntl і відступ

**Comment by Katrinkleina** [comment]
Хтось знає точно #2

**Comment by OsakaBlue** [comment]
Єдина інформація щодо #2 була на парі, коли вона сказала, що здача буде або 7 або 14

**Comment by OsakaBlue** [comment]
Скільки має бути позицій в одній рубриці?

**Comment by Darochka** [comment]
Має бути 6-8 позицій
