### ISSUE TITLE
Анотації

### ISSUE THREAD

**Issue by Katrinkleina** [Katrinkleina/-_21#3]
Чи потрібно писати в "цій статті"

**Comment by OsakaBlue** [comment]
Ні, мені здається, що ці слова заборонені при написанні анотацій

**Comment by Darochka** [comment]
Не потрібно, бо ми описуємо лише статті, а не інші види документів.

**Comment by OsakaBlue** [comment]
На якій мові має бути анотація, якщо стаття іноземною мовою?

**Comment by nataliakendzerska** [comment]
Навіть якщо стаття іноземною мовою, анотацію ми пишемо українською.
