### ISSUE TITLE
Нормативна база

### ISSUE THREAD

**Issue by Katrinkleina** [Katrinkleina/-_21#5]
Необхідні назви документів для написання висновку

**Comment by Darochka** [comment]
[Скорочення слів у бібліографічоому.pdf](https://github.com/Katrinkleina/-_21/files/1919469/default.pdf)

**Comment by IrynaPanashiy** [comment]
[Приклади опису згідно ДСТУ.docx](https://github.com/Katrinkleina/-_21/files/1919471/default.docx)

**Comment by Darochka** [comment]
Ще є інший перелік документів. Його має @IrynaPanashiy

**Comment by Katrinkleina** [comment]
Добре, дякую

**Comment by Katrinkleina** [comment]
Fixed#5

**Comment by Katrinkleina** [comment]
Fixes #8

**Comment by Katrinkleina** [comment]
develop #5

**Comment by Katrinkleina** [comment]
Fix #5
