### ISSUE TITLE
Кількість

### ISSUE THREAD

**Issue by OsakaBlue** [Katrinkleina/-_21#6]
Скільки людей здали 1шу частину курсової і почали 2гу?

**Comment by Katrinkleina** [comment]
Другу ще не починав ніхто

**Comment by Katrinkleina** [comment]
Спитай у @Darochka

**Comment by OsakaBlue** [comment]
@Darochka, ще дійсно ніхто не починав?

**Comment by Katrinkleina** [comment]
Ні, ще висновок і вступ треба

**Comment by IrynaPanashiy** [comment]
І нам ще не пояснювали,як писати другий розділ

**Comment by nataliakendzerska** [comment]
@OsakaBlue 
[Методичні рекомендації для написання курсових робіт.pdf](https://github.com/Katrinkleina/-_21/files/1919504/default.pdf)

**Comment by OsakaBlue** [comment]
fixed

**Comment by Darochka** [comment]
Другий розділ є найпроблемнішим. Бо ми не маємо поняття як їх робити
