### ISSUE TITLE
Розділ 2 

### ISSUE THREAD

**Issue by nataliakendzerska** [Katrinkleina/-_21#9]
Яку інформацію потрібно вмістити в розділ 2 курсової роботи?

**Comment by OsakaBlue** [comment]
Це має пояснювати ГГ. Чи вона вже казала?

**Comment by Darochka** [comment]
Г. Г. буде це пояснювати в середу і в четвер після 14:00

**Comment by Katrinkleina** [comment]
різні покажчики, нехай @OsakaBlue  знайде

**Comment by nataliakendzerska** [comment]
fixed

**Comment by nataliakendzerska** [comment]
Closes #9

**Comment by nataliakendzerska** [comment]
fixes#9

**Comment by nataliakendzerska** [comment]
fixes #9
